name: Integration Tests
on:
  workflow_dispatch:

jobs:
    integrations-tests:
      strategy:
        matrix:
          os: [macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            brew install docker docker-machine
            brew install --cask virtualbox@5.0.12
            docker-machine create default
            brew services restart docker-machine
            eval "$(docker-machine env default)"
            python3 -m pip install --upgrade pip
            pip3 install setuptools wheel twine
            pip3 install .
        - name: check if docker is running
          run: docker ps
        - name: run freshenv
          run: freshenv --help
        - name: provision busybox
          run: freshenv provision -f freshenv-busybox -c ls -p '["3001","3002"]'
        - name: view freshenv
          run: freshenv view
