name: Integration Tests
on:
  workflow_dispatch:

jobs:
    integrations-tests:
      strategy:
        matrix:
          os: [macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            brew install hyperkit
            brew install minikube
            brew install docker
            brew install docker-compose
            minikube start
            eval $(minikube docker-env)
            echo "`minikube ip` docker.local" | sudo tee -a /etc/hosts > /dev/null
            docker run hello-world
            python3 -m pip install --upgrade pip
            pip3 install setuptools wheel twine
            pip3 install .
        - name: run freshenv
          run: freshenv --help
        - name: provision busybox
          run: freshenv provision -f freshenv-busybox -c ls -p '["3001","3002"]'
        - name: view freshenv
          run: freshenv view
