name: Package Release
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install setuptools wheel twine
          sudo snap install snapcraft --classic
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          SNAPCRAFT_SECRET: ${{ secrets.SNAPCRAFT_SECRET }}
        run: |
          python3 setup.py sdist bdist_wheel
          twine upload dist/*
          snapcraft
          snapcraft upload --release=stable *.snap

